export const PROGRAMS_SV = [
  "ZBASS - Tekniskt basår",
  "ZBARD - Tekniskt basår på distans",
  "TKARK - Arkitektur",
  "TKMAS - Maskinteknik, civilingenjör",
  "TKBIO - Bioteknik, civilingenjör",
  "TKTFY - Teknisk fysik",
  "TKDAT - Datateknik, civilingenjör",
  "TKKEF - Kemiteknik med fysik",
  "TKIEK - Industriell ekonomi",
  "TKMED - Medicinteknik, civilingenjör",
  "TKDES - Teknisk design, civilingenjör",
  "TKKMT - Kemiteknik, civilingenjör",
  "TKSAM - Samhällsbyggnadsteknik, civilingenjör",
  "TKGBS - Globala system",
  "TKELT - Elektroteknik, civilingenjör",
  "TKAUT - Automation och mekatronik",
  "TKTEM - Teknisk matematik",
  "TKTKE - Teknisk kemi",
  "TKATK - Arkitektur och teknik",
  "TKITE - Informationsteknik",
  "KPLOL - Lärande och ledarskap, kompletterande pedagogisk utbildning",
  "TKTDE - Teknisk design",
  "TKMSK - Maskinteknik",
  "TIDAL - Datateknik, högskoleingenjör",
  "TIMEL - Mekatronik",
  "TIMAL - Maskinteknik, högskoleingenjör",
  "TIDSL - Design och produktutveckling",
  "TISAM - Samhällsbyggnadsteknik, högskoleingenjör",
  "TIKEL - Kemiteknik, högskoleingenjör",
  "TIELL - Elektroteknik, högskoleingenjör",
  "TIEPL - Ekonomi och produktionsteknik",
  "MPICT - Informations- och kommunikationsteknik",
  "MPAEM - Materialteknik",
  "MPSOF - Software engineering and technology - utveckling och implementering av mjukvara",
  "MPSCM - Supply chain management",
  "MPEPO - Hållbara elkraftsystem och elektromobilitet",
  "MPDSD - Arkitektur och planering för hållbar framtid",
  "MPARC - Arkitektur och stadsbyggnad",
  "MPMAR - Sjöfartens organisation och ledning",
  "MPMEI - Innovationsledning",
  "MPMCN - Materialkemi",
  "MPENM - Matematik och beräkningsvetenskap",
  "MPPDE - Produktutveckling",
  "MPDCM - Organisering och ledning i bygg- och fastighetssektorn",
  "MPSYS - Systemteknik, reglerteknik och mekatronik",
  "MPPHS - Fysik",
  "MPTSE - Industriell ekologi",
  "MPWPS - Trådlös teknik, fotonik och rymdteknik",
  "MPHPC - Högpresterande datorsystem",
  "MPCSN - Datorer, nätverk och system",
  "MPSES - Hållbara energisystem",
  "MPDES - Teknisk design, masterprogram",
  "MPBIO - Bioteknik, masterprogram",
  "MPCAS - Komplexa adaptiva system",
  "MPISC - Innovativ och hållbar kemiteknik",
  "MPQOM - Kvalitets- och verksamhetsutveckling",
  "MPALG - Datavetenskap - algoritmer, programspråk och logik",
  "MPPEN - Produktionsutveckling",
  "MPDSC - Data Science och AI",
  "MPIDE - Interaktionsdesign",
  "MPNAT - Nanoteknologi",
  "MPLOL - Lärande och ledarskap",
  "MPCSC - Datorer, system och cybersäkerhet",
  "MPIEE - Infrastruktur och miljöteknik",
  "MPMOB - Mobilitetsteknik",
  "MPEES - Inbyggda elektroniksystem",
  "MPBDP - Entreprenörskap och affärsdesign",
  "MPMED - Medicinteknik, masterprogram",
  "MPAME - Tillämpad mekanik",
  "MPSEB - Konstruktionsteknik och byggnadsteknologi",
  "MPSOV - Ljud och vibrationer",
  "FVIID - Fartygsbefäl klass VII: behörighetsgivande praktikår",
  "TISJL - Sjöingenjör",
  "TSJKL - Sjökapten",
  "SBVII - Sjöbefäl klass VII",
  "TAFFS - Affärsutveckling och entreprenörskap inom samhällsbyggnadsteknik",
  "TSILO - Internationell logistik",
  "FRIST - Fristående kurs",
  "MBATT - Batteriteknik - aktuell kunskap och framtida utmaningar",
  "SPRAK - Fackspråk och kommunikation",
  "TRACKS - Tracks initiative",
  "MTS - Människa - teknik - samhälle"
] as const;

export const PROGRAMS_EN = [
  "ZBASS - A Foundation Year",
  "ZBARD - Distance-Based Foundation Year",
  "TKARK - Architecture",
  "TKMAS - Mechanical Engineering",
  "TKBIO - Bioengineering",
  "TKTFY - Engineering Physics",
  "TKDAT - Computer Science and Engineering",
  "TKKEF - Chemical Engineering with Engineering Physics",
  "TKIEK - Industrial Engineering and Management",
  "TKMED - Biomedical Engineering",
  "TKDES - Industrial Design Engineering",
  "TKKMT - Chemical Engineering",
  "TKSAM - Civil Engineering",
  "TKGBS - Global Systems Engineering",
  "TKELT - Electrical Engineering",
  "TKAUT - Automation and Mechatronics Engineering",
  "TKTEM - Engineering Mathematics",
  "TKTKE - Engineering Chemistry",
  "TKATK - Architecture and Engineering",
  "TKITE - Software Engineering",
  "KPLOL - Learning and Leadership, Supplementary Study Programme",
  "TKTDE - Industrial Design Engineering",
  "TKMSK - Mechanical Engineering",
  "TIDAL - Computer Engineering",
  "TIMEL - Mechatronics Engineering",
  "TIMAL - Mechanical Engineering",
  "TIDSL - Product Design Engineering",
  "TISAM - Civil and Environmental Engineering",
  "TIKEL - Chemical Engineering",
  "TIELL - Electrical Engineering",
  "TIEPL - Industrial Management and Production Engineering",
  "MPICT - Information and Communication Technology",
  "MPAEM - Materials Engineering",
  "MPSOF - Software Engineering and Technology",
  "MPSCM - Supply Chain Management",
  "MPEPO - Sustainable Electric Power Engineering and Electromobility",
  "MPDSD - Architecture and Planning Beyond sustainability",
  "MPARC - Architecture and Urban Design",
  "MPMAR - Maritime Management",
  "MPMEI - Management and Economics of Innovation",
  "MPMCN - Materials Chemistry",
  "MPENM - Engineering Mathematics and Computational Science",
  "MPPDE - Product Development",
  "MPDCM - Design and Construction Project Management",
  "MPSYS - Systems, Control and Mechatronics",
  "MPPHS - Physics",
  "MPTSE - Industrial Ecology",
  "MPWPS - Wireless, Photonics and Space Engineering",
  "MPHPC - High-performance Computer Systems",
  "MPCSN - Computer Systems and Networks",
  "MPSES - Sustainable Energy Systems",
  "MPDES - Industrial Design Engineering, MSc Progr",
  "MPBIO - Biotechnology",
  "MPCAS - Complex Adaptive Systems",
  "MPISC - Innovative and Sustainable Chemical Engineering",
  "MPQOM - Quality and operations Management",
  "MPALG - Computer Science - Algorithms, Languages and Logic",
  "MPPEN - Production Engineering",
  "MPDSC - Data Science and AI",
  "MPIDE - Interaction Design and Technologies",
  "MPNAT - Nanotechnology",
  "MPLOL - Learning and Leadership",
  "MPCSC - Computer Systems and Cybersecurity",
  "MPIEE - Infrastructure and Environmental Engineering",
  "MPMOB - Mobility Engineering",
  "MPEES - Embedded Electronic System Design",
  "MPBDP - Entrepreneurship and Business Design",
  "MPMED - Biomedical Engineering, MSc Progr",
  "MPAME - Applied Mechanics",
  "MPSEB - Structural Engineering and Building Technology",
  "MPSOV - Sound and Vibration",
  "FVIID - Deck Officer Class VII: Seafaring Qualification",
  "TISJL - Marine Engineering",
  "TSJKL - Nautical Science",
  "SBVII - Deck Officer and Engineer Officer, Class VII",
  "TAFFS - Business Development and Entrepreneurship",
  "TSILO - International Logistics",
  "FRIST - Freestanding Course",
  "MBATT - Battery Technologies - current knowledge and future challenges",
  "SPRAK - Language and Communication",
  "TRACKS - Tracks Initiative",
  "MTS - Humans, Technology, Society"
] as const;